# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=60)),
                ('Humidity', models.IntegerField(default=40)),
                ('date_log', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='incubation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Batch One', max_length=9)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('last_rotation', models.DateTimeField(verbose_name='Last rotation')),
            ],
        ),
        migrations.AddField(
            model_name='dht',
            name='incub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.incubation'),
        ),
    ]
