# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20170410_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='incubation',
            name='last_rotation',
        ),
        migrations.AddField(
            model_name='rotation',
            name='incub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.incubation'),
        ),
    ]
