# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20170411_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotation',
            old_name='date_log',
            new_name='last_rotation',
        ),
    ]
