# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='password',
            new_name='from_password',
        ),
        migrations.AddField(
            model_name='email',
            name='to_email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
