# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_auto_20170516_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='end_image',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='rotation',
            name='start_image',
            field=models.CharField(default='', max_length=254),
        ),
    ]
