# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-07-11 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_auto_20170516_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='RHT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktherm_temp', models.FloatField(default=60)),
                ('amb_temp', models.FloatField(default=60)),
                ('rh', models.FloatField(default=60)),
                ('inc_temp', models.FloatField(default=60)),
                ('date_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incubation',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='rht',
            name='incub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.incubation'),
        ),
    ]
