# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-07-14 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_auto_20200711_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.BooleanField(default=False)),
                ('address', models.EmailField(max_length=100)),
            ],
        ),
    ]
