# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-07-23 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubation',
            name='RH',
            field=models.FloatField(default=65),
        ),
        migrations.AddField(
            model_name='incubation',
            name='lockdown',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='incubation',
            name='stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incubation',
            name='total_days',
            field=models.IntegerField(default=21),
        ),
    ]
